export const POST_LOGIN_TABS = [
  {
    key: 'Status',
    label: 'STATUS',
    route: 'Status',
    iconFamily: 'material',
    iconName: 'person',
    title: 'STATUS',
    subtitle: 'SYSTEM ONLINE',
  },
  {
    key: 'Quests',
    label: 'QUESTS',
    route: 'Quests',
    iconFamily: 'community',
    iconName: 'sword-cross',
    title: 'QUESTS',
    subtitle: 'Quest board syncing',
  },
  {
    key: 'Log',
    label: 'LOG',
    route: 'Log',
    iconFamily: 'material',
    iconName: 'history-edu',
    title: 'LOG',
    subtitle: 'Choose what to train',
  },
  {
    key: 'Analytics',
    label: 'ANALYTICS',
    route: 'Analytics',
    iconFamily: 'material',
    iconName: 'insights',
    title: 'ANALYTICS',
    subtitle: 'Data pipeline active',
  },
  {
    key: 'Coach',
    label: 'COACH',
    route: 'Coach',
    iconFamily: 'community',
    iconName: 'account-tie',
    title: 'COACH',
    subtitle: 'Training AI calibrating',
  },
];

export const STATUS_ATTRIBUTE_CARDS = [
  {
    key: 'STR',
    value: 24,
    progress: '45%',
    delta: '+2 (45%)',
    iconFamily: 'community',
    iconName: 'dumbbell',
    route: 'StatStr',
    wide: false,
  },
  {
    key: 'DEX',
    value: 18,
    progress: '25%',
    delta: '+1 (25%)',
    iconFamily: 'material',
    iconName: 'flash-on',
    route: 'StatDetailPlaceholder',
    wide: false,
  },
  {
    key: 'SPD',
    value: 32,
    progress: '60%',
    delta: '+3 (60%)',
    iconFamily: 'community',
    iconName: 'run-fast',
    route: 'StatDetailPlaceholder',
    wide: false,
  },
  {
    key: 'STM',
    value: 45,
    progress: '90%',
    delta: '+5 (90%)',
    iconFamily: 'material',
    iconName: 'favorite',
    route: 'StatDetailPlaceholder',
    wide: false,
  },
  {
    key: 'INT',
    value: 89,
    progress: '12%',
    delta: '+0 (12%)',
    iconFamily: 'material',
    iconName: 'psychology',
    route: 'StatInt',
    wide: true,
  },
];

export const LOG_TRAINING_ACTIONS = [
  {
    key: 'INT',
    title: 'INT (Mind)',
    description: 'Study & quizzes',
    route: 'LogIntEntry',
    iconFamily: 'community',
    iconName: 'brain',
  },
  {
    key: 'STR',
    title: 'STR (Strength)',
    description: 'Strength training',
    route: 'LogStrEntry',
    iconFamily: 'community',
    iconName: 'dumbbell',
  },
  {
    key: 'STM',
    title: 'STM (Stamina)',
    description: 'Endurance & cardio',
    route: 'LogStmEntry',
    iconFamily: 'material',
    iconName: 'favorite',
  },
  {
    key: 'SPD',
    title: 'SPD (Speed)',
    description: 'Sprints & agility',
    route: 'LogSpdEntry',
    iconFamily: 'community',
    iconName: 'run-fast',
  },
  {
    key: 'DEX',
    title: 'DEX (Dexterity)',
    description: 'Reflex & control',
    route: 'LogDexEntry',
    iconFamily: 'material',
    iconName: 'flash-on',
  },
  {
    key: 'Food',
    title: 'Food (HP)',
    description: 'Meals & nutrition',
    route: 'LogFoodEntry',
    iconFamily: 'community',
    iconName: 'food-apple',
  },
  {
    key: 'Sleep',
    title: 'Sleep (MP)',
    description: 'Rest & recovery',
    route: 'LogSleepEntry',
    iconFamily: 'material',
    iconName: 'bedtime',
  },
];

export const LOG_ENTRY_ROUTES = LOG_TRAINING_ACTIONS.map((item) => item.route);
